general.import = [
    "~/.config/alacritty/current-theme.toml"
]
[window]

# opacity = 0.9
blur = true 
title = "пегадинья"
dynamic_title = false
padding.x = 5
padding.y = 25
decorations = "Transparent"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal.family = "IosevkaTerm NF"
bold.family = "IosevkaTerm NF"
italic.family = "IosevkaTerm NF"
bold_italic.family = "IosevkaTerm NF"

size = 15.0

[env]
TERM="xterm-256color"
