#  ██████████ ████     ████ ██     ██ ██     ██
# ░░░░░██░░░ ░██░██   ██░██░██    ░██░░██   ██ ░██    ░██░░██ ██ ░██░██    ░██ ░░██ ██ ░██    ░██ ░░███  ░██░██    ░██  ░░███
#     ░██    ░██  ░░█   ░██░██    ░██   ██░██
#     ░██    ░██   ░    ░██░██    ░██  ██ ░░██
#     ░██    ░██        ░██░░███████  ██   ░░██
#     ░░     ░░         ░░  ░░░░░░░  ░░     ░░
unbind r
bind r source-file ~/.tmux.conf

# set -ga terminal-overrides ",-256color:Tc"
set -sg  escape-time  0
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set-option -g history-limit 10000

set -g prefix C-s
set -g mouse on

#start with 1 window
set -g base-index 1

vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
bind-key l select-pane -R

set -g @fuzzback-bind /

bind-key -r -T prefix       M-Up              resize-pane -U 5
bind-key -r -T prefix       M-Down            resize-pane -D 5
bind-key -r -T prefix       M-Left            resize-pane -L 5
bind-key -r -T prefix       M-Right           resize-pane -R 5
bind-key -r -T prefix       C-Up              resize-pane -U
bind-key -r -T prefix       C-Down            resize-pane -D
bind-key -r -T prefix       C-Left            resize-pane -L
bind-key -r -T prefix       C-Right           resize-pane -R

bind g display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

bind f display-popup 
bind c new-window -c "#{pane_current_path}"

unbind %
bind \\ split-window -h -c "#{pane_current_path}"

unbind \"
bind - split-window -c "#{pane_current_path}"

unbind f
unbind t

bind 'f' display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"

bind 'j' display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t" bind 'c' display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

set-option -g status-position top


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'roosta/tmux-fuzzback'

# Panes Style
set -g pane-border-lines simple
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=black'
set-option -g pane-border-indicators arrows

# # Status style.
set -g status-style "fg=#BBC3D4,bg=#1e1e1e"
set -g status-right "#[fg=#BBC3D4,bg=#1e1e1e] #[fg=##d1d1a1,bg=#1e1e1e]"
set -g status-left  ""

set -g status-position bottom
set -g status-justify left
setw -g window-status-current-format "#[fg=colour214,bold] #I:#W "

# # Window style.
set -g window-status-format " #I:#W "
set -g window-status-separator " "


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
